# Name: Nicholas Fotinakes
# Date: 2022-03-22
# Title: Lab3 Makefile
# Description: This is the make file for all steps of Lab 3

all: lab3step1 lab3step2 lab3step3

lab3step1: lab3step1.c
	gcc lab3step1.c -o lab3step1 -Wall -Werror

lab3step2: lab3step2.c
	gcc lab3step2.c -o lab3step2 -Wall -Werror

lab3step3: lab3step3.c
	gcc lab3step3.c -o lab3step3 -Wall -Werror

clean:
	rm -f lab3step1 lab3step2 lab3step3
