# Name: Nicholas Fotinakes
# Date: 2022-03-29
# Title: Lab4 Makefile
# Description: This is the makefile for Lab 4 FIFO simulation
# to compile fifo program using queue package

all: fifo

fifo: fifo.c 
	gcc fifo.c queue.c node.c -o fifo -Wall -Werror

clean:
	rm -f fifo
