# Name: Nicholas Fotinakes
# Date: 2022-03-15
# Title: Lab2 Step 5 Make File
# Description: Makefile for both parts of Lab 2

# Build both lab2 and lab2step5
all: lab2 lab2step5

# Make command to build part 1 (steps 1-4)
lab2: lab2.c
	gcc lab2.c -o lab2 -Wall -Werror

# Make command to build part 2 (step 5)
lab2step5: lab2step5.c
	gcc lab2step5.c -o lab2step5 -Wall -Werror

# clean
clean: rm -f lab2 lab2step5
